#! python 3

import re as re, pyperclip as py

# TODO: Create a regex for phone numbers
phoneRegex=re.compile(r'''
(
((\d\d\d)|(\(\d\d\d\)))?                      #area code (optional)
(\s|-)                       #first seperator
\d\d\d                       #first 3 digits
-                            #seperator
\d\d\d\d                     #last 4 digits
(((ext(\.)?\s)|x)            #extension word part(optional)
(\d{2,5}))? 
)                            #extension number part(optional
''', re.VERBOSE)

# TODO: Create a regex for email addresses
emailRegex = re.compile(r'''
# some.+_things@(\d{2,5))?.com
[a-zA-Z0-9_.+]+         # name part
@                       # @ symbol
[a-zA-Z0-9_.+]+         # domain name part

''', re.VERBOSE)

# TODO: Get the text off the clipboard
text = py.paste()

# TODO: Extract the email/phone numbers from the text
extractedPhone= phoneRegex.findall(text)
extractedEmail= emailRegex.findall(text)

allPhoneNumbers =[]
for phoneNumber in extractedPhone:
    allPhoneNumbers.append(phoneNumber[0])
print(allPhoneNumbers)
print(extractedEmail)
# TODO: Copy the extracted email/phone numbers to the clipboard
results = '\n'.join(allPhoneNumbers) + '\n' +'\n'.join(extractedEmail)
py.copy(results)
